name: Build X11+OpenVR+OpenXR

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9
    - name: Prepare Environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y fuse cmake pkg-config fontconfig libasound2-dev libxkbcommon-dev libxkbcommon-x11-0 libxkbcommon-x11-dev libopenxr-dev libfontconfig-dev libdbus-1-dev libspa-0.2-dev libx11-6 libxext6 libxrandr2 libx11-dev libxext-dev libxrandr-dev libopenvr-dev libopenvr-api1
    - name: Build
      run: cargo build --verbose --release --no-default-features --features=x11,openvr,openxr
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        path: ./target/release/wlx-overlay-s
        name: wlx-overlay-s
